use_frameworks!

platform :ios, '8.0'

target 'EPSGBox_Example' do
  pod 'EPSGBox', :path => '../'

  target 'EPSGBox_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
